### PR TITLE
Added Github Action

### PR DESCRIPTION
**Pull request by danielaei**
I created a GitHub action for this project and added the following actions to get started:
Caching dependencies
Automatic release.

### CODE REVIEW

**Comment by jwillinghalpern** [comment]
Hi @danieldevel thanks for your contribution and interest in this project. Are you a filemaker developer as well? Have you used fm-mock before?

I have a couple questions/thoughts:
1. I see you specified the action runs on pushes to "main", but this repo has no "main" branch. Does that automatically map to "master"?
2. I see it does `npm run example-multi`, but that is just there as an example to users, and not needed as part of a release.
3. How does `Songmu/tagpr@v1` work? I assume as part of an automated release the version number should be incremented, but historically I usually manually increment the version when I do npm releases using `npm version minor` for example. I'm not sure how this all fits together as part of publishing to npm.

Thanks again.

**Comment by jwillinghalpern** [comment]
I'm going close this specific request since it doesn't appear to be tested or match the repo, but I'll refer to this as starter code later when I decide to automate releases.

**Comment by danielaei** [comment]
> Hi @danieldevel thanks for your contribution and interest in this project. Are you a filemaker developer as well? Have you used fm-mock before?
> 
> I have a couple questions/thoughts:
> 
> 1. I see you specified the action runs on pushes to "main", but this repo has no "main" branch. Does that automatically map to "master"?
> 2. I see it does `npm run example-multi`, but that is just there as an example to users, and not needed as part of a release.
> 3. How does `Songmu/tagpr@v1` work? I assume as part of an automated release the version number should be incremented, but historically I usually manually increment the version when I do npm releases using `npm version minor` for example. I'm not sure how this all fits together as part of publishing to npm.
> 
> Thanks again.

Hello again, thank you for responding. 
Honestly, not yet. However, two weeks ago, my friends discussed it, and I was a listener. A couple of days ago, I came across your project, and I thought it would be a good idea for me to contribute something meaningful.

1. Initially, I was working on the 'main' branch, but I realize now that you're using the 'master' branch. It will work with pull request.
2. You're correct, I added that as a test, but I forgot to remove it afterwards.
3. I understand now. I made another adjustment: now the tags on GitHub and NPM are automatically incremented simultaneously during the release process. As for the major, minor, and patch versions, you should specify which one you want in the comments.

Don't forget, you need to include the NPM_TOKEN to publish on NPM.
I've just updated the [repository](https://github.com/danieldevel/fm-mock/tree/feature/github-action), so you can take a look. If you have any questions, feel free to ask. I'm here.

**Comment by jwillinghalpern** [comment]
Right on, I appreciate your work. I'll take a look soon.

**Comment by jwillinghalpern** [comment]
Hey Daniel, I'm considering simplifying this workflow a bit to just a NPM publish (with testing) that runs whenever I create a release (and maybe a separate action can be added to create releases somehow, perhaps if I bump the `version` in package.json). I'm less keen on using commit messages to bump the version automatically.

What do you think of the below workflow. `actions/setup-node` should cache between jobs using  `actions/cache` under the hood [according to this](https://github.com/actions/setup-node?tab=readme-ov-file#caching-global-packages-data).

Does this look reasonable to you? If so I think I can edit this PR and merge it.

```yaml
name: Publish To NPM

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
```

Best,
Josh

**Comment by danielaei** [comment]
Hey Josh,

That's fantastic news! If you've had a chance to test it out and everything is working smoothly, we're good to go. Let's move forward with it!

**Comment by jwillinghalpern** [comment]
Thanks again for this @danieldevel! This should make my life a bit easier. I'd be interested in doing this other repo too, if you'd like to submit the same action pr there too (the simplified NPM release version preferred for now): https://github.com/jwillinghalpern/fm-gofer

**Comment by danielaei** [comment]
It's amazing I'll do it sure, Just let me time @jwillinghalpern

**Pull request merged**
